### ISSUE TITLE
The DP-12 blocks Safehouse Progession extract to safehouse

### ISSUE THREAD

**Issue by ShivanReaper** [DesiQuintans/sosiggun_soren#1]
Picked up a DP-12 that had dropped in Supply Raid and tried to extract, but clicking on extract to safehouse option would ask to confirm, but would not extract even if you confirmed.  As soon as I dropped the gun, I could extract.  Tested this by spawning a dp-12 in my safehouse, put it in a backpack slot, left the safehouse and started a new supply raid mission.  Loaded my deployment load out, which included the dp-12, captured one point, and tried to extract, which I was unable to do,  I then dropped the DP-12, after which I could extract normally.

**Comment by DesiQuintans** [comment]
I noticed this separately as well, but then when I tried again in another session it worked fine (and of course, I was able to bring the DP12 back with me in the first place). Probably best to remove this for now just to avoid issues.

**Comment by DesiQuintans** [comment]
Fixed in v3.2.0.

**Comment by DesiQuintans** [comment]
FYI the DP12 is back in the newest version, v3.4.0. This is because it wasn't the DP12 blocking extraction, it's just a rare bug with SafehouseProgression (I've had it happen with all vanilla items in my belt, and dropping the items did not help).

The author of that mod made a new version called [Safehouse for H3MP](https://h3vr.thunderstore.io/package/NGA/Safehouse_for_H3MP/) and recommends it even for solo players because you can separately save/load your loadout and safehouse to self-debug these things.
